### PR TITLE
boilerplate and content added

### PR DESCRIPTION
**Pull request by Keon24**

### CODE REVIEW

**Comment by Eugal-git** [comment]
Hello Keon,  .

**Comment by Eugal-git** [comment]
Hello Keon Powell. You are doing well , it is showing a good structure but there are just a few corrections that can be adjusted 

To start with your <li> element. It should always be wrapped inside the <ul> or <ol>

2.  On the <p> tag. It is written there it should be "the"

3. Please also ensure that your class names are consistent.
Here is a more updated code

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Software Security Developer Portfolio</title>
</head>
<body>
    <header>
        <h1>Software Security Developer</h1>
        <nav role="navigation">
            <ul>
                <li>Tryhackme</li>
                <li>Hackthebox</li>
                <li>LetsDefend</li>
            </ul>
        </nav>
    </header>
    <main>
        <section class="software-section">
          <div class="cyber-info">
            <h1>2025</h1>
            <h2>Break in Tech</h2>
            <p>2025 will be the year we will succeed</p>
          </div>
        </section>
    </main>
</body>
</html>

**Comment by Keon24** [comment]
Sorry I thought I deleted lesson 7 I was going to redo it

**Comment by Eugal-git** [comment]
Hello Keon Powell, it's ok. Once done you can send it through for review. 

Thank you

Eugetee

**Pull request closed without merging**
